### ISSUE TITLE
Toast message does not expire while clicking on other pages.

### ISSUE THREAD

**Issue by akhtarmunir1143** [realrashid/sweet-alert#79] opened 2020-04-27 12:07 UTC
Dear.
A simple issue i have been noticing maybe I am wrong. But the issue is when I return back with a toast_error message it doesn't expire at all. Wherever I click the same message appears on other pages as well.

Just like laravel uses the flash session messages which expires after a reload. In your package this doesn't work for me.

When I logout the flash session expires.

The problem might be here:
`Swal.fire({!! Session::pull('alert.config') !!})`

You are pullling it from session and in this case you might have put the messages in actual session and not in flash session. A flash session expires after a single redirect.

Thanks

**Comment by realrashid** [comment] 2020-07-17 18:03
Duplicate of #81

**Closed by realrashid** 2020-07-17 18:03 UTC
