### ISSUE TITLE
Sweetalert working well in my local pc. but it has a problem when im running my project in another pc.

### ISSUE THREAD

**Issue by fariqM** [realrashid/sweet-alert#110] opened 2020-12-30 14:44 UTC
Required parameter $imageUrl follows optional parameter $title

im not using any addimage() or image() alert. just basic success and fail alert. but its show me error parameter of $imageUrl

**Comment by realrashid** [comment] 2021-01-12 07:14
Duplicate of #108

**Closed by realrashid** 2021-01-12 07:14 UTC
