### ISSUE TITLE
Don't autoclose Middleware alerts

### ISSUE THREAD

**Issue by maicol07** [realrashid/sweet-alert#87] opened 2020-06-07 11:03 UTC
## Detailed description

Allow middleware alerts to not autoclose after X ms

## Context

User can read calmly the message

## Possible implementation

Split the ENV variables into 2: one for toasts and one for alerts.  
Allow to set the ENV variables to null, 0 or something like that to disable the middleware alert timer.

## Your environment

Include as many relevant details about the environment you experienced the bug in and how to reproduce it.

*   Version used (e.g. Laravel v5.6, SweetAlert2 v7.18.0): Laravel v7.14.1, SweetAlert2 v3.1.4
*   Operating system and version (e.g. Ubuntu 16.04, Windows 7): Windows 10 2004 x64

**Comment by realrashid** [comment] 2020-06-11 19:40
Hey @maicol07 ,
The issue is fixed in v3.1.5.

**Closed by realrashid** 2020-06-11 19:40 UTC

**Comment by maicol07** [comment] 2020-08-01 14:44
@realrashid This isn't working... Alert gets fired with the timer property:

```javascript
Swal.fire({
    "title":"Text.",
    "text":"",
    "timer":5000,
    "width":"32rem",
    "heightAuto":true,
    "padding":"1.25rem",
    "showConfirmButton":true,
    "showCloseButton":false,
    "customClass":{
        "container":null,
        "popup":null,
        "header":null,
        "title":null,
        "closeButton":null,
        "icon":null,
        "image":null,
        "content":null,
        "input":null,
        "actions":null,
        "confirmButton":"mdc-button mdc-button--raised",
        "cancelButton":"mdc-button",
        "footer":null
    },
    "icon":"info"
});
```

 This is the JS code printed into the page

**Comment by trollfalgar** [comment] 2020-08-29 08:21
I'm using version 3.1.6 and have this issue.
The toasts is not closing after the especified time.
